language: ruby
env:
  - DB=mysql
before_install:
  - gem install bundler
before_script:
  - mysql -e 'create database retro_test'
  - rake db:migrate RAILS_ENV=test  
rvm:
  - 1.9.3
script: bundle exec rake
notifications:
  email:
    - mobile-stat@cwi.com.br
